#!/usr/bin/env python3
"""
Export the TESTS array from tests.html to a downloadable JSON file.

Reads en/tests.html, parses the JavaScript TESTS array (including nested
phases arrays for intervention entries), and writes a clean JSON file
with all fields: id, name, domain, groups, D, r2, verdict, kind,
narrative, image, source, date, url, phases.

The JSON is regenerated by the auto-scanner on every run, so it stays
in sync with the registry.
"""

import os, re, json
from datetime import datetime

def parse_tests_array(html_text):
    """Parse the TESTS JavaScript array from HTML into a Python list of dicts."""
    m = re.search(r'const\s+TESTS\s*=\s*\[(.*?)\n\];', html_text, re.DOTALL)
    if not m:
        return []
    body = m.group(1)
    
    entries = []
    i = 0
    while i < len(body):
        brace = body.find('{', i)
        if brace < 0:
            break
        depth = 0
        j = brace
        in_str = False
        esc = False
        while j < len(body):
            c = body[j]
            if esc:
                esc = False
            elif c == '\\':
                esc = True
            elif c == '"':
                in_str = not in_str
            elif not in_str:
                if c == '{':
                    depth += 1
                elif c == '}':
                    depth -= 1
                    if depth == 0:
                        break
            j += 1
        if depth != 0:
            break
        
        entry_str = body[brace:j+1]
        entry = parse_entry(entry_str)
        if entry:
            entries.append(entry)
        i = j + 1
    
    return entries

def parse_entry(text):
    """Parse a single JS object literal into a Python dict."""
    result = {}
    
    m = re.search(r'id:"((?:[^"\\]|\\.)*)"', text)
    if m: result['id'] = m.group(1).replace('\\"', '"').replace('\\\\', '\\')
    
    m = re.search(r'name:"((?:[^"\\]|\\.)*)"', text)
    if m: result['name'] = m.group(1).replace('\\"', '"').replace('\\\\', '\\')
    
    m = re.search(r'domain:"([^"]*)"', text)
    if m: result['domain'] = m.group(1)
    
    m = re.search(r'groups:\[([^\]]*)\]', text)
    if m:
        result['groups'] = [g.strip().strip('"') for g in m.group(1).split(',') if g.strip()]
    
    m = re.search(r'\bD:(null|[\d.]+)', text)
    if m:
        val = m.group(1)
        result['D'] = None if val == 'null' else float(val)
    
    m = re.search(r'\br2:(null|[\d.]+)', text)
    if m:
        val = m.group(1)
        result['r2'] = None if val == 'null' else float(val)
    
    m = re.search(r'verdict:"([^"]*)"', text)
    if m: result['verdict'] = m.group(1)
    
    m = re.search(r'kind:"([^"]*)"', text)
    if m: result['kind'] = m.group(1)
    
    m = re.search(r'narrative:"((?:[^"\\]|\\.)*)"', text)
    if m: result['narrative'] = m.group(1).replace('\\"', '"').replace('\\\\', '\\')
    
    m = re.search(r'image:(null|"[^"]*")', text)
    if m:
        val = m.group(1)
        result['image'] = None if val == 'null' else val.strip('"')
    
    m = re.search(r'source:"([^"]*)"', text)
    if m: result['source'] = m.group(1)
    
    m = re.search(r'date:"([^"]*)"', text)
    if m: result['date'] = m.group(1)
    
    m = re.search(r'url:"((?:[^"\\]|\\.)*)"', text)
    if m: result['url'] = m.group(1).replace('\\"', '"').replace('\\\\', '\\')
    
    # phases (for intervention entries)
    m = re.search(r'phases:\[(.*?)\]', text, re.DOTALL)
    if m:
        phases_body = m.group(1)
        phases = []
        for phase_m in re.finditer(r'\{([^{}]*)\}', phases_body):
            phase_text = phase_m.group(1)
            phase = {}
            lm = re.search(r'label:"([^"]*)"', phase_text)
            if lm: phase['label'] = lm.group(1)
            dm = re.search(r'\bD:([\d.]+)', phase_text)
            if dm: phase['D'] = float(dm.group(1))
            km = re.search(r'kind:"([^"]*)"', phase_text)
            if km: phase['kind'] = km.group(1)
            phases.append(phase)
        result['phases'] = phases
    
    return result if result.get('id') else None

def export_json(html_path, json_path):
    """Export TESTS from html_path to json_path."""
    with open(html_path, encoding='utf-8') as f:
        html = f.read()
    
    tests = parse_tests_array(html)
    
    output = {
        'exported_at': datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%SZ'),
        'total_tests': len(tests),
        'fields': ['id', 'name', 'domain', 'groups', 'D', 'r2', 'verdict', 
                   'kind', 'narrative', 'image', 'source', 'date', 'url', 'phases'],
        'tests': tests,
    }
    
    with open(json_path, 'w', encoding='utf-8') as f:
        json.dump(output, f, indent=2, ensure_ascii=False)
    
    print(f'  ✓ {json_path}: {len(tests)} tests exported')
    return tests

if __name__ == '__main__':
    import sys
    base = sys.argv[1] if len(sys.argv) > 1 else '.'
    for lang in ['en', 'ru']:
        html_path = os.path.join(base, lang, 'tests.html')
        json_path = os.path.join(base, lang, 'tests.json')
        if os.path.exists(html_path):
            export_json(html_path, json_path)
        else:
            print(f'  ✗ {html_path} not found')
